name: TheRunners
version: ${project.version}
main: me.sf90.therunners.TheRunners
api-version: '1.16'
authors: [SF90]
description: TheRunners is a running competition event plugin.
commands:
  runners:
    description: Main command for the runners plugin.
    aliases: [runner, therunners, "koşuyarışı"]
    usage: /runners <join | leave>
  runnersadmin:
    description: Admin command for the runners plugin.
    aliases: [therunnersadmin, kyadmin]
    permission: therunners.admin
    usage: /runnersadmin <reload | setspawn>
