# TheRunners by SF90
# Time equations are to be set in seconds.
# DO NOT REMOVE PLACEHOLDERS LIKE %d, %s, etc.
general:
  eventStartDelay: 20
  eventJoinDelay: 20
  eventPeriod: 150
  startCountdown: 5

rewardCommands:
  - "eco give %s 10000000"